
create schema IF NOT EXISTS  tasks;

CREATE TABLE if NOT EXISTS  tasks.tasks (
    task_id        integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    description    varchar(1024),
    is_completed   bit,
    assigned_to    varchar(124)
);